# Generated by Django 5.2.9 on 2026-01-06 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('expertise_domain', models.CharField(choices=[('AUDIT', 'Audit'), ('FINANCE', 'Finance'), ('INSURANCE', 'Assurance'), ('PROCUREMENT', 'Achats'), ('SALES', 'Ventes'), ('DESIGN', 'Design/Création'), ('HEALTH', 'Santé'), ('LOGISTICS', 'Logistique'), ('MARCOM', 'Marcom'), ('TECH', 'Tech'), ('MEDIA', 'Media'), ('RETAIL', 'Retail'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('key_challenges', models.JSONField(default=list)),
                ('technical_skills', models.JSONField(default=list)),
                ('interpersonal_skills', models.JSONField(default=list)),
                ('years_experience_required', models.IntegerField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('INTERIM', 'Intérim Management'), ('FULL_TIME', 'Temps plein'), ('PART_TIME', 'Temps partiel'), ('FREELANCE', 'Freelance'), ('OTHER', 'Autre')], default='OTHER', max_length=50)),
                ('published_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('reward_display', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to='organizations.organizationmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='organizations.organization')),
            ],
            options={
                'db_table': 'job_openings',
                'indexes': [models.Index(fields=['organization', 'status'], name='job_opening_organiz_999931_idx'), models.Index(fields=['expertise_domain'], name='job_opening_experti_6bd080_idx'), models.Index(fields=['published_date'], name='job_opening_publish_148cca_idx')],
            },
        ),
    ]
