# Generated by Django 5.2.9 on 2026-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('TPE/PME', 'TPE/PME'), ('ETI', 'ETI'), ('GRAND_GROUP', 'Grand groupe')], max_length=50, null=True),
        ),
    ]
