# Generated by Django 5.2.9 on 2026-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobopening_organization_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='organization_size',
            field=models.CharField(blank=True, choices=[('TPE/PME', 'TPE/PME'), ('ETI', 'ETI'), ('GRAND_GROUP', 'Grand groupe'), ('STARTUP', 'Startup'), ('ASSOCIATION', 'Association/ONG')], max_length=50, null=True),
        ),
    ]
