# Generated by Django 5.2.11 on 2026-02-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobopening_organization_size'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='activity_sector',
            field=models.CharField(blank=True, choices=[('BANKING', 'Banque et Services Financiers'), ('INSURANCE_SECTOR', 'Assurance'), ('CONSULTING_AUDIT', 'Conseil et Audit'), ('REAL_ESTATE_PROMOTION', 'Promotion immobilière'), ('REAL_ESTATE_ASSET', "Gestion d'actifs (Asset Management)"), ('REAL_ESTATE_LUXURY', 'Immobilier de prestige'), ('LUXURY', 'Luxe (Haute couture, maroquinerie, horlogerie, joaillerie)'), ('RETAIL_DISTRIBUTION', 'Retail / Distribution'), ('FOOD_INDUSTRY', 'Agroalimentaire'), ('COSMETICS_BEAUTY', 'Cosmétiques et Beauté'), ('IT_SOFTWARE', 'Informatique et Software (IT)'), ('TELECOM', 'Télécommunications'), ('ADVERTISING', 'Publicité'), ('STREAMING', 'Streaming'), ('VIDEO_GAMES', 'Jeux vidéo'), ('PRESS', 'Presse'), ('ENERGY_UTILITIES', 'Énergie et Utilities'), ('HEALTH_PHARMA', 'Santé et Pharma'), ('AUTOMOTIVE_AEROSPACE', 'Automobile et Aéronautique'), ('CHEMISTRY_MATERIALS', 'Chimie et Matériaux'), ('HOSPITALITY', 'Hôtellerie et Restauration'), ('TRANSPORT_LOGISTICS', 'Transports et Logistique'), ('LEISURE_CULTURE', 'Loisirs et Culture')], help_text="Secteur d'activité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='company_context',
            field=models.CharField(blank=True, choices=[('STARTUP', 'Start-up / Lancement'), ('SCALEUP', 'Hyper-croissance (Scale-up)'), ('INTERNATIONALIZATION', 'Internationalisation'), ('DIVERSIFICATION', 'Diversification'), ('CRUISING', 'Vitesse de croisière'), ('SUCCESSION', 'Transmission / Succession'), ('RESTRUCTURING', 'Redressement judiciaire'), ('REPUTATION_CRISIS', 'Crise de réputation'), ('TECH_DISRUPTION', 'Rupture technologique')], help_text="Contexte d'entreprise", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='contract_types',
            field=models.JSONField(default=list, help_text='Types de contrat (liste de valeurs ContractType, max 2)'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('TOP_MANAGEMENT', 'Top Management : 12 - 18 ans'), ('C_LEVEL', 'C-Level (Comex) : 18 - 25+ ans'), ('BOARD', 'Board (Conseil) : 25+ ans')], help_text="Niveau d'expérience souhaité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='location_canton',
            field=models.CharField(blank=True, help_text='Canton', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='location_city',
            field=models.CharField(blank=True, help_text='Ville', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='location_country',
            field=models.CharField(default='Suisse', help_text='Pays', max_length=100),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='mandate_context',
            field=models.CharField(blank=True, choices=[('POSITION_CREATION', 'Création de poste'), ('REPLACEMENT', 'Remplacement'), ('MATERNITY_LEAVE', 'Congés maternité')], help_text='Contexte du mandat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='recruitment_process',
            field=models.JSONField(default=list, help_text='Process de recrutement: liste de {role: string, objective: string}'),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='salary_benefits',
            field=models.TextField(blank=True, help_text='Avantages', null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='salary_fixed',
            field=models.CharField(blank=True, help_text='Rémunération fixe', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='salary_other',
            field=models.TextField(blank=True, help_text='Autres', null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='salary_variable',
            field=models.CharField(blank=True, help_text='Rémunération variable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='shareholder_structure',
            field=models.CharField(blank=True, choices=[('LISTED_FAMILY', 'Listée - Familial'), ('LISTED_FUND', 'Listée - Financier (fonds)'), ('LISTED_STATE', 'Listée - État'), ('UNLISTED_FAMILY', 'Non listée - Familial'), ('UNLISTED_FUND', 'Non listée - Financier (fonds)'), ('UNLISTED_EMPLOYEE', 'Non listée - Salarié')], help_text="Structure de l'actionnariat", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='description',
            field=models.TextField(help_text='Description du poste (5 lignes max)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='expertise_domain',
            field=models.CharField(blank=True, choices=[('AUDIT_CONSULTING', 'Audit et conseil'), ('FINANCE', 'Finance'), ('INSURANCE', 'Assurance'), ('LEGAL_TAX', 'Juridique et fiscalité'), ('SALES', 'Ventes'), ('RETAIL', 'Retail'), ('MARCOM', 'Marcom'), ('MEDIA', 'Média'), ('PROCUREMENT', 'Achats'), ('LOGISTICS_SUPPLY', 'Logistique et supply chain'), ('QUALITY', 'Qualité'), ('TECH_IT', 'Tech / IT'), ('DATA_AI', 'Data et IA'), ('DESIGN_CREATION', 'Design / Création'), ('HEALTH', 'Santé'), ('HR', 'RH'), ('RD', 'R&D'), ('TECH', 'Technique / Ingénierie')], help_text='Expertise métier', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='interpersonal_skills',
            field=models.JSONField(default=list, help_text='3 compétences relationnelles fondamentales'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='key_challenges',
            field=models.JSONField(default=list, help_text='3 enjeux clefs (liste de valeurs KeyChallenge)'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='organization_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='reward_display',
            field=models.CharField(help_text='Récompense affichée (ex: €1,500)', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='technical_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='title',
            field=models.CharField(help_text='Intitulé de poste', max_length=255),
        ),
        migrations.AddIndex(
            model_name='jobopening',
            index=models.Index(fields=['activity_sector'], name='job_opening_activit_2bd760_idx'),
        ),
        migrations.AddIndex(
            model_name='jobopening',
            index=models.Index(fields=['company_context'], name='job_opening_company_b7bf28_idx'),
        ),
    ]
