# Generated by Django 5.2.12 on 2026-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobopening_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='reward_display',
            field=models.CharField(help_text="Champ legacy d'affichage (ex: 1500 Points)", max_length=100),
        ),
    ]
