# Generated by Django 5.2.9 on 2026-01-06 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('expertise_domain', models.CharField(choices=[('AUDIT', 'Audit'), ('FINANCE', 'Finance'), ('INSURANCE', 'Assurance'), ('PROCUREMENT', 'Achats'), ('SALES', 'Ventes'), ('DESIGN', 'Design/Création'), ('HEALTH', 'Santé'), ('LOGISTICS', 'Logistique'), ('MARCOM', 'Marcom'), ('TECH', 'Tech'), ('MEDIA', 'Media'), ('RETAIL', 'Retail'), ('OTHER', 'Autre')], default='TECH', max_length=50)),
                ('search_criteria', models.JSONField(default=list)),
                ('technical_skills', models.JSONField(default=list)),
                ('interpersonal_skills', models.JSONField(default=list)),
                ('linkedin_headline', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin_summary', models.TextField(blank=True, null=True)),
                ('linkedin_experience', models.JSONField(blank=True, null=True)),
                ('linkedin_education', models.JSONField(blank=True, null=True)),
                ('linkedin_skills', models.JSONField(blank=True, null=True)),
                ('linkedin_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('consent_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='organizations.organization')),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_context', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.candidate')),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='jobs.jobopening')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='organizations.organization')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('reason_category', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='organizations.organizationmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_events', to='organizations.organization')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='referrals.referral')),
            ],
            options={
                'db_table': 'referral_status_events',
            },
        ),
        migrations.CreateModel(
            name='RewardOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_display_snapshot', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='organizations.organization')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_outcome', to='referrals.referral')),
            ],
            options={
                'db_table': 'reward_outcomes',
            },
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['organization', 'email'], name='candidates_organiz_54f3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['expertise_domain'], name='candidates_experti_c908fd_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['organization', 'job_opening'], name='referrals_organiz_9ec42e_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['organization', 'referrer'], name='referrals_organiz_a87ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['organization', 'status'], name='referrals_organiz_9afbd3_idx'),
        ),
        migrations.AddIndex(
            model_name='referralstatusevent',
            index=models.Index(fields=['organization', 'referral', 'created_at'], name='referral_st_organiz_c6d219_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardoutcome',
            index=models.Index(fields=['organization', 'status'], name='reward_outc_organiz_77d185_idx'),
        ),
    ]
