# Generated by Django 5.2.9 on 2026-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='profile_motivation',
            field=models.TextField(blank=True, help_text='Pourquoi recommander ce profil pour ce poste?', null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='relationship_type',
            field=models.CharField(choices=[('COMPANY', 'Ancien collègue (même entreprise)'), ('HIERARCHICAL', 'Lien hiérarchique'), ('ALUMNI', 'Alumni (même école/université)'), ('OTHER', 'Autre')], default='OTHER', help_text='Type de relation avec le candidat', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='supporting_materials',
            field=models.JSONField(blank=True, default=list, help_text='Liens vers des matériaux de support (articles, conférences, photos, etc.)', null=True),
        ),
    ]
