# Generated by Django 5.2.11 on 2026-02-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('referrals', '0002_referral_profile_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='expertise_domain',
            field=models.CharField(choices=[('AUDIT_CONSULTING', 'Audit et conseil'), ('FINANCE', 'Finance'), ('INSURANCE', 'Assurance'), ('LEGAL_TAX', 'Juridique et fiscalité'), ('SALES', 'Ventes'), ('RETAIL', 'Retail'), ('MARCOM', 'Marcom'), ('MEDIA', 'Média'), ('PROCUREMENT', 'Achats'), ('LOGISTICS_SUPPLY', 'Logistique et supply chain'), ('QUALITY', 'Qualité'), ('TECH_IT', 'Tech / IT'), ('DATA_AI', 'Data et IA'), ('DESIGN_CREATION', 'Design / Création'), ('HEALTH', 'Santé'), ('HR', 'RH'), ('RD', 'R&D'), ('TECH', 'Technique / Ingénierie')], default='TECH', max_length=50),
        ),
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(help_text='Score final hybride (0-100)')),
                ('rule_score', models.IntegerField(help_text='Score basé sur les règles (0-100)')),
                ('llm_score', models.IntegerField(help_text="Score basé sur l'analyse LLM (0-100)")),
                ('grade', models.CharField(choices=[('A', 'Excellent (80+)'), ('B', 'Bon (60-79)'), ('C', 'Moyen (40-59)'), ('D', 'Faible (<40)')], max_length=1)),
                ('expertise_match', models.IntegerField(default=0)),
                ('experience_match', models.IntegerField(default=0)),
                ('interpersonal_skills_match', models.IntegerField(default=0)),
                ('technical_skills_match', models.IntegerField(default=0)),
                ('referral_quality', models.IntegerField(default=0)),
                ('llm_strengths', models.JSONField(default=list, help_text='Points forts identifiés par le LLM')),
                ('llm_gaps', models.JSONField(default=list, help_text='Points faibles identifiés par le LLM')),
                ('llm_summary', models.TextField(blank=True, help_text="Résumé de l'analyse LLM")),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('llm_model_used', models.CharField(blank=True, help_text='Modèle LLM utilisé', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scores', to='organizations.organization')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='referrals.referral')),
            ],
            options={
                'db_table': 'candidate_scores',
                'ordering': ['-final_score'],
                'indexes': [models.Index(fields=['organization', 'final_score'], name='candidate_s_organiz_8ef7ff_idx'), models.Index(fields=['organization', 'grade'], name='candidate_s_organiz_8d66f3_idx')],
            },
        ),
    ]
