# Generated by Django 5.2.11 on 2026-03-02 22:48

import apps.referrals.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_candidate_expertise_domain_candidatescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING_CONSENT', 'En attente de consentement'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='CandidateConsentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.referrals.models._default_consent_expiry)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_token', to='referrals.referral')),
            ],
            options={
                'db_table': 'candidate_consent_tokens',
            },
        ),
    ]
